### ISSUE TITLE
[Issue] Multi-instances for multiple view

### ISSUE THREAD

**Issue by jaku-jaku** [rohanpsingh/mujoco-python-viewer#16]
Thanks for the great work, and I am trying to transform my script to use this lib from mujoco-py. 
But I realized that this library seems to be incapable to create multiple instances:
      For example, a -1 observer view, and 0,1 for stereo vision.
      
I am wondering if there is any workaround in-mind related to this?

Best
Jack

**Comment by rohanpsingh** [comment]
Hi @jaku-jaku 
Do you mean rendering multiple windows at the same time?
Indeed this is not supported yet, but should be straightforward to implement.

**Comment by jaku-jaku** [comment]
> Do you mean rendering multiple windows at the same time?
> Indeed this is not supported yet, but should be straightforward to implement.

Yeah, or running multiple instances of the viewer from different angles.
mujoco-py seems to be capable to host different viewer at same time. 

But, yeah, I'm gonna try to figure out how to make it work. 

Thanks! 

PS: I do notice this codebase is somewhat similar to the way how mujoco-py implement MjViewer, and a really good starting base for me. Thanks!
