### ISSUE TITLE
Testing

### ISSUE THREAD

**Issue by pab47** [rohanpsingh/mujoco-python-viewer#17]
I tested the code on python3 on mac (intel) and I had to do 3 changes to get it work

1) remove import imagio (package is not needed and I was not able to install it anyway)
2) line 500 and 533 I had to change is to ==

**Comment by rohanpsingh** [comment]
Hi @pab47 

1. `imageio` is in fact needed to capture screenshots (Press `T`). Looking at the docs, it seems it is supported on macOS
2. Yes, that should be changed to `==`. I just pushed a commit for this.

Let me know if you still face a problem.

**Comment by pab47** [comment]
I am unable to install imagio on mac. pip install imagio give me this message
ERROR: Could not find a version that satisfies the requirement imagio (from versions: none)
ERROR: No matching distribution found for imagio

I don't really need the screenshot functionality. I can find a workaround if needed. Please close this ticket. Thanks!
