### ISSUE TITLE
How to display arrow when dragging?

### ISSUE THREAD

**Issue by gyuta** [rohanpsingh/mujoco-python-viewer#19]
This is nice repository. This code will help me a lot.

But I have a question about displaying arrow when dragging.

In example in readme.md, arrow to indicate force is displayed like this.

![161459985-a47e74dc-92c9-4a0b-99fc-92d1b5b04163](https://user-images.githubusercontent.com/53563180/185560189-5b3246c9-2214-488b-904e-682da6266547.gif)

https://user-images.githubusercontent.com/53563180/185560247-a8f1c8f9-95a5-450d-bd3f-c6554323b6c6.mp4

However, it shows a box and prevent me from undastanfing the direction of the force in my trial.
I also trys left/right ctrl keys.

Do you have any idea to fix this?

thanks

this is my environment
python 3.7.12
glfw                 2.5.4
mujoco-python-viewer 0.1.1

**Comment by rohanpsingh** [comment]
Hi, you are applying torques. If you double-click on an object, and then hold the ctrl key and use your RIGHT mouse button, you can apply forces! 
Let me know if that helps :)

**Comment by gyuta** [comment]
Thanks for quick reply :)
it works!!
