### ISSUE TITLE
Not able to get view to render in real time.

### ISSUE THREAD

**Issue by Robokan** [rohanpsingh/mujoco-python-viewer#30]
I am running a simulation with a time step of 0.001 and gravity of -9.8. My model isn't very tall just 0.4m. When I use your viewer it puts everything into slow motion. If I turn off help it gets faster but still in slow motion. Pressing D seems to make it just go faster than real life. Why is it not moving at the same rate it would in real life? How do I get it to render in real time?

**Comment by rohanpsingh** [comment]
Hi @Robokan 
The viewer does not ensure real time simulation speed. If it is faster than real-time, you need to introduce a time delay by yourself in your code after each call to `render`.

**Comment by Robokan** [comment]
I am having the opposite problem it is rendering too slowly. Pressing D speeds it up but skips frames.

**Comment by Robokan** [comment]
Ok I figured it out. Somehow I was calling render  twice. It works now.

**Comment by Robokan** [comment]
This is a great viewer BTW. Thanks for creating it!

**Comment by rohanpsingh** [comment]
Nice!
