### ISSUE TITLE
Make size of joint visualization objects smaller?

### ISSUE THREAD

**Issue by studywolf** [rohanpsingh/mujoco-python-viewer#31]
Hello,

I'm trying to find a way to reduce the size of the joint visualization objects. They were much smaller in mujoco-py, is there a parameter I can set here that will control the size?
Thanks!

**Comment by rohanpsingh** [comment]
Hi @studywolf 

Did you try tweaking the `jointlength` and `jointwidth` attributes of your model XML under [visual/scale](https://mujoco.readthedocs.io/en/stable/XMLreference.html#visual-scale) ?

**Comment by studywolf** [comment]
guhh, sorry, i should have thought of this. yes that does it. thanks for the quick reply!
